# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rsna_ab_trauma',
                'doc_host': 'https://ChrisRichardMiles.github.io',
                'git_url': 'https://github.com/ChrisRichardMiles/rsna_ab_trauma',
                'lib_path': 'rsna_ab_trauma'},
  'syms': {'rsna_ab_trauma.core': {'rsna_ab_trauma.core.foo': ('core.html#foo', 'rsna_ab_trauma/core.py')}}}
